import type { ImpostorCategory } from "$lib/games/impostor/types";

type ImpostorRawWordEntry = [word: string, hintOne: string, hintTwo: string, hintThree: string];

const createCategory = (
    id: string,
    name: string,
    description: string,
    words: ImpostorRawWordEntry[],
): ImpostorCategory => ({
    id,
    name,
    description,
    words: words.map(([word, hintOne, hintTwo, hintThree]) => ({
        word,
        hints: [hintOne, hintTwo, hintThree],
    })),
});

export const impostorCategories: ImpostorCategory[] = [
    createCategory("1", "Tiere", "Bekannte Tiere aus aller Welt", [
        ["Hund", "Bellt", "Vier Beine", "Haustier"],
        ["Katze", "Miau", "Schnurrt", "Haustier"],
        ["Elefant", "Rüssel", "Groß", "Savanne"],
        ["Löwe", "Mähne", "Raubtier", "Savanne"],
        ["Giraffe", "Langer Hals", "Gefleckt", "Afrika"],
        ["Delfin", "Meer", "Intelligent", "Springt"],
        ["Pinguin", "Schwarzweiß", "Watschelt", "Antarktis"],
        ["Känguru", "Beutel", "Springt", "Australien"],
        ["Eule", "Nacht", "Große Augen", "Fliegt"],
        ["Fuchs", "Rotbraun", "Schlau", "Wald"],
        ["Schildkröte", "Panzer", "Langsam", "Alt"],
        ["Zebra", "Streifen", "Savanne", "Pferdeartig"],
        ["Bär", "Winterschlaf", "Groß", "Tatzen"],
        ["Hase", "Lange Ohren", "Hoppelt", "Karotte"],
        ["Schmetterling", "Bunte Flügel", "Leicht", "Insekt"],
        ["Krokodil", "Schuppen", "Fluss", "Gefährlich"],
        ["Panda", "Schwarzweiß", "Bambus", "China"],
        ["Hai", "Flosse", "Meer", "Raubfisch"],
        ["Flamingo", "Rosa", "Steht", "Wasser"],
        ["Otter", "Fluss", "Verspielt", "Schwimmt"],
        ["Chamäleon", "Farbwechsel", "Echse", "Zunge"],
        ["Pfau", "Bunt", "Federrad", "Stolz"],
        ["Biene", "Summt", "Honig", "Stachel"],
        ["Gorilla", "Affenartig", "Stark", "Dschungel"],
        ["Wal", "Riesig", "Ozean", "Bläst"],
    ]),
    createCategory("2", "Essen", "Beliebte Gerichte und Lebensmittel", [
        ["Pizza", "Italienisch", "Käse", "Teig"],
        ["Burger", "Fast Food", "Brötchen", "Patty"],
        ["Sushi", "Japanisch", "Reis", "Roh"],
        ["Pasta", "Nudeln", "Italienisch", "Soße"],
        ["Tacos", "Mexikanisch", "Gefüllt", "Maistortilla"],
        ["Croissant", "Französisch", "Blättrig", "Frühstück"],
        ["Döner", "Fladenbrot", "Spieß", "Salat"],
        ["Paella", "Spanisch", "Pfanne", "Reis"],
        ["Ramen", "Japanisch", "Brühe", "Nudelschüssel"],
        ["Lasagne", "Geschichtet", "Ofen", "Nudeln"],
        ["Currywurst", "Deutsch", "Soße", "Imbiss"],
        ["Falafel", "Kichererbse", "Frittiert", "Vegetarisch"],
        ["Risotto", "Cremig", "Reis", "Italienisch"],
        ["Burrito", "Gerollt", "Mexikanisch", "Gefüllt"],
        ["Pfannkuchen", "Süß", "Flach", "Pfanne"],
        ["Apfelstrudel", "Apfel", "Ofen", "Dessert"],
        ["Gulasch", "Eintopf", "Paprika", "Ungarisch"],
        ["Quiche", "Herzhaft", "Ofen", "Eier"],
        ["Müsli", "Frühstück", "Flocken", "Schüssel"],
        ["Waffel", "Süß", "Karomuster", "Gebäck"],
        ["Knödel", "Rund", "Beilage", "Sättigend"],
        ["Bratwurst", "Grill", "Deutsch", "Wurst"],
        ["Gazpacho", "Kalt", "Tomate", "Spanisch"],
        ["Nudelsalat", "Kalt", "Party", "Schüssel"],
        ["Käsespätzle", "Käse", "Pfanne", "Alpen"],
    ]),
    createCategory("3", "Berufe", "Berufe, die man schnell erraten kann", [
        ["Arzt", "Krankenhaus", "Diagnose", "Weiße Kittel"],
        ["Bäcker", "Früh auf", "Ofen", "Brot"],
        ["Gärtner", "Pflanzen", "Erde", "Gießkanne"],
        ["Pilot", "Cockpit", "Flugzeug", "Wolken"],
        ["Polizist", "Uniform", "Gesetz", "Streife"],
        ["Schauspieler", "Bühne", "Rolle", "Kamera"],
        ["Musiker", "Melodie", "Auftritt", "Instrument"],
        ["Fotograf", "Kamera", "Bilder", "Objektiv"],
        ["Kellner", "Restaurant", "Serviert", "Tablett"],
        ["Architekt", "Gebäude", "Pläne", "Entwurf"],
        ["Anwalt", "Gericht", "Mandant", "Recht"],
        ["Mechaniker", "Werkstatt", "Motor", "Reparatur"],
        ["Friseur", "Schere", "Haare", "Salon"],
        ["Journalist", "Artikel", "Recherche", "Nachrichten"],
        ["Koch", "Küche", "Rezepte", "Topf"],
        ["Schneider", "Stoff", "Nadel", "Maßband"],
        ["Zahnarzt", "Bohrer", "Praxis", "Zähne"],
        ["Programmierer", "Code", "Computer", "Tastatur"],
        ["Elektriker", "Strom", "Kabel", "Sicherung"],
        ["Tauchlehrer", "Meer", "Flossen", "Unterwasser"],
        ["Astronaut", "Weltraum", "Helm", "Rakete"],
        ["Bibliothekar", "Bücher", "Leise", "Regale"],
        ["Florist", "Blumen", "Strauß", "Duft"],
        ["Taxifahrer", "Stadt", "Fahrgast", "Lenkrad"],
        ["Detektiv", "Spur", "Rätsel", "Lupe"],
    ]),
    createCategory("4", "Verkehrsmittel", "Fahrzeuge auf Land, Wasser und in der Luft", [
        ["Fahrrad", "Pedale", "Zwei Räder", "Lenker"],
        ["Zug", "Schienen", "Waggons", "Bahnhof"],
        ["U-Bahn", "Unterirdisch", "Haltestelle", "Stadt"],
        ["Segelboot", "Wind", "Mast", "Wasser"],
        ["Hubschrauber", "Rotor", "Luft", "Schwebt"],
        ["Straßenbahn", "Schienen", "Stadt", "Oberleitung"],
        ["Rakete", "Weltraum", "Start", "Feuer"],
        ["Wohnmobil", "Camping", "Fährt", "Schläft"],
        ["Tretroller", "Stehend", "Rollt", "Lenkstange"],
        ["Fähre", "Überfahrt", "Wasser", "Anleger"],
        ["Skateboard", "Brett", "Rollen", "Tricks"],
        ["Heißluftballon", "Korb", "Brenner", "Schwebt"],
        ["Traktor", "Acker", "Große Reifen", "Landwirtschaft"],
        ["Kanu", "Paddel", "Schmal", "Fluss"],
        ["Lastwagen", "Ladung", "Groß", "Fernstraße"],
        ["Motorroller", "Helm", "Stadt", "Zweirad"],
        ["Schnellboot", "Motor", "Wasser", "Rasant"],
        ["Seilbahn", "Kabine", "Berg", "Höhe"],
        ["Kreuzfahrtschiff", "Deck", "Urlaub", "Meer"],
        ["Schlitten", "Schnee", "Kufen", "Winter"],
        ["Jetski", "Wasser", "Motor", "Spritzig"],
        ["Gondel", "Venedig", "Kanal", "Lang"],
        ["Lieferwagen", "Pakete", "Kasten", "Straße"],
        ["Doppeldeckerbus", "Zwei Ebenen", "Stadt", "Touristen"],
        ["Kajak", "Paddel", "Sitzmulde", "Wasser"],
    ]),
    createCategory("5", "Instrumente", "Musikinstrumente mit klaren Erkennungsmerkmalen", [
        ["Gitarre", "Saiten", "Zupfen", "Holz"],
        ["Klavier", "Tasten", "Pedale", "Flügel"],
        ["Geige", "Bogen", "Saiten", "Kinn"],
        ["Trompete", "Blech", "Bläst", "Jazz"],
        ["Schlagzeug", "Rhythmus", "Sticks", "Trommeln"],
        ["Flöte", "Holzbläser", "Quer", "Luft"],
        ["Harfe", "Viele Saiten", "Groß", "Zupfen"],
        ["Saxophon", "Jazz", "Goldfarben", "Blasinstrument"],
        ["Cello", "Tief", "Bogen", "Zwischen den Knien"],
        ["Ukulele", "Klein", "Saiten", "Hawaii"],
        ["Akkordeon", "Balg", "Tasten", "Faltet sich"],
        ["Klarinette", "Schwarz", "Holzbläser", "Mundstück"],
        ["Mundharmonika", "Tasche", "Blasen", "Metall"],
        ["Xylophon", "Stäbe", "Schlägel", "Klingt hell"],
        ["Posaune", "Zug", "Blech", "Tief"],
        ["Oboe", "Doppelrohrblatt", "Orchester", "Holz"],
        ["Banjo", "Rund", "Saiten", "Country"],
        ["Tamburin", "Schellen", "Hand", "Rhythmus"],
        ["Tuba", "Sehr groß", "Blech", "Tief"],
        ["Dudelsack", "Sack", "Schottland", "Drohnen"],
        ["Maracas", "Schütteln", "Paar", "Latin"],
        ["Kontrabass", "Riesig", "Tief", "Saiten"],
        ["Triangel", "Dreieck", "Metall", "Kleiner Schlägel"],
        ["Bongos", "Zwei Trommeln", "Hand", "Latin"],
        ["Mandoline", "Klein", "Saiten", "Zupfinstrument"],
    ]),
    createCategory("6", "Reiseziele", "Bekannte Orte für Urlaub und Städtereisen", [
        ["Paris", "Eiffelturm", "Frankreich", "Romantik"],
        ["Rom", "Kolosseum", "Italien", "Antike"],
        ["Tokio", "Japan", "Neon", "Metropole"],
        ["New York", "Wolkenkratzer", "USA", "Broadway"],
        ["Barcelona", "Gaudí", "Strand", "Spanien"],
        ["Venedig", "Kanäle", "Gondeln", "Italien"],
        ["Sydney", "Opernhaus", "Australien", "Hafen"],
        ["Kairo", "Pyramiden", "Ägypten", "Wüste"],
        ["Reykjavik", "Island", "Nordlicht", "Vulkane"],
        ["Kapstadt", "Tafelberg", "Südafrika", "Küste"],
        ["Bali", "Indonesien", "Tempel", "Insel"],
        ["Santorini", "Weiße Häuser", "Griechenland", "Klippen"],
        ["Amsterdam", "Fahrräder", "Kanäle", "Niederlande"],
        ["Prag", "Karlsbrücke", "Tschechien", "Altstadt"],
        ["Lissabon", "Straßenbahn", "Portugal", "Hügel"],
        ["Marrakesch", "Souk", "Marokko", "Gewürze"],
        ["Wien", "Sachertorte", "Österreich", "Walzer"],
        ["Dubrovnik", "Stadtmauer", "Kroatien", "Adria"],
        ["Bangkok", "Thailand", "Straßenessen", "Tempel"],
        ["Island", "Geysire", "Inselstaat", "Nordatlantik"],
        ["Malediven", "Atolle", "Türkises Wasser", "Luxus"],
        ["Lappland", "Schnee", "Polarlichter", "Rentiere"],
        ["Hawaii", "Surfen", "Vulkan", "Pazifik"],
        ["Seoul", "Südkorea", "Technologie", "Großstadt"],
        ["Petra", "Felsenstadt", "Jordanien", "Wüste"],
    ]),
    createCategory("7", "Fantasiewesen", "Magische und mythische Wesen", [
        ["Drache", "Feuer", "Schuppen", "Flügel"],
        ["Einhorn", "Horn", "Pferd", "Magisch"],
        ["Meerjungfrau", "Fischschwanz", "Meer", "Singt"],
        ["Phoenix", "Feuer", "Vogel", "Wiedergeburt"],
        ["Yeti", "Schnee", "Groß", "Gebirge"],
        ["Zentaur", "Mensch", "Pferd", "Mythologie"],
        ["Vampir", "Nacht", "Blut", "Reißzähne"],
        ["Werwolf", "Vollmond", "Verwandlung", "Fell"],
        ["Fee", "Flügel", "Zauber", "Klein"],
        ["Troll", "Brücke", "Groß", "Märchen"],
        ["Pegasus", "Flügel", "Pferd", "Himmel"],
        ["Kobold", "Frech", "Klein", "Versteckt"],
        ["Minotaurus", "Labyrinth", "Stierkopf", "Griechenland"],
        ["Greif", "Adler", "Löwe", "Mischwesen"],
        ["Sphinx", "Rätsel", "Löwenkörper", "Ägypten"],
        ["Golem", "Lehm", "Belebt", "Beschützer"],
        ["Kraken", "Tentakel", "Meer", "Monster"],
        ["Nixe", "Wasser", "Zauberhaft", "See"],
        ["Zyklop", "Ein Auge", "Riese", "Mythologie"],
        ["Hexe", "Besen", "Zaubertrank", "Hut"],
        ["Geist", "Unsichtbar", "Spuk", "Schwebt"],
        ["Elf", "Spitze Ohren", "Wald", "Magisch"],
        ["Ork", "Grimmig", "Fantasy", "Krieger"],
        ["Gargoyle", "Stein", "Dach", "Wächter"],
        ["Basilisk", "Schlange", "Blick", "Tödlich"],
    ]),
];
